// Code generated by Wire protocol buffer compiler, do not edit.
// Source: helloworld.HelloReply in helloworld.proto
import Foundation
import Wire

/**
 * The response message containing the greetings.
 */
public struct HelloReply {

    public var message: String
    public var unknownFields: Data = .init()

    public init(message: String) {
        self.message = message
    }

}

#if !WIRE_REMOVE_EQUATABLE
extension HelloReply : Equatable {
}
#endif

#if !WIRE_REMOVE_HASHABLE
extension HelloReply : Hashable {
}
#endif

#if swift(>=5.5)
extension HelloReply : Sendable {
}
#endif

extension HelloReply : ProtoMessage {

    public static func protoMessageTypeURL() -> Swift.String {
        return "type.googleapis.com/helloworld.HelloReply"
    }

}

extension HelloReply : Proto3Codable {

    public init(from reader: Wire.ProtoReader) throws {
        var message: Swift.String = ""

        let token = try reader.beginMessage()
        while let tag = try reader.nextTag(token: token) {
            switch tag {
            case 1: message = try reader.decode(Swift.String.self)
            default: try reader.readUnknownField(tag: tag)
            }
        }
        self.unknownFields = try reader.endMessage(token: token)

        self.message = message
    }

    public func encode(to writer: Wire.ProtoWriter) throws {
        try writer.encode(tag: 1, value: self.message)
        try writer.writeUnknownFields(unknownFields)
    }

}

#if !WIRE_REMOVE_CODABLE
extension HelloReply : Codable {

    public init(from decoder: Swift.Decoder) throws {
        let container = try decoder.container(keyedBy: Wire.StringLiteralCodingKeys.self)
        self.message = try container.decode(Swift.String.self, forKey: "message")
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var container = encoder.container(keyedBy: Wire.StringLiteralCodingKeys.self)
        let includeDefaults = encoder.protoDefaultValuesEncodingStrategy == .include

        if includeDefaults || !self.message.isEmpty {
            try container.encode(self.message, forKey: "message")
        }
    }

}
#endif
