// Code generated by Wire protocol buffer compiler, do not edit.
// Source: helloworld.Greeter in helloworld.proto
package io.grpc.examples.helloworld

import com.squareup.wire.GrpcCall
import com.squareup.wire.Service

/**
 * The greeting service definition.
 */
public interface GreeterClient : Service {
  /**
   * Sends a greeting.
   */
  public fun SayHello(): GrpcCall<HelloRequest, HelloReply>
}
