// Code generated by Wire protocol buffer compiler, do not edit.
// Source: helloworld.Greeter in helloworld.proto
package io.grpc.examples.helloworld

import com.squareup.wire.GrpcCall
import com.squareup.wire.GrpcClient
import com.squareup.wire.GrpcMethod

/**
 * The greeting service definition.
 */
public class GrpcGreeterClient(
  private val client: GrpcClient,
) : GreeterClient {
  /**
   * Sends a greeting.
   */
  public override fun SayHello(): GrpcCall<HelloRequest, HelloReply> = client.newCall(GrpcMethod(
      path = "/helloworld.Greeter/SayHello",
      requestAdapter = HelloRequest.ADAPTER,
      responseAdapter = HelloReply.ADAPTER
  ))
}
