// Code generated by Wire protocol buffer compiler, do not edit.
// Source: helloworld.HelloRequest in helloworld.proto
package io.grpc.examples.helloworld

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Unit
import kotlin.jvm.JvmField
import okio.ByteString

/**
 * The request message containing the user's name.
 */
public class HelloRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
  )
  public val name: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<HelloRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  public override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is HelloRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (name != other.name) return false
    return true
  }

  public override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + name.hashCode()
      super.hashCode = result
    }
    return result
  }

  public override fun toString(): String {
    val result = mutableListOf<String>()
    result += """name=${sanitize(name)}"""
    return result.joinToString(prefix = "HelloRequest{", separator = ", ", postfix = "}")
  }

  public fun copy(name: String = this.name, unknownFields: ByteString = this.unknownFields):
      HelloRequest = HelloRequest(name, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<HelloRequest> = object : ProtoAdapter<HelloRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      HelloRequest::class, 
      "type.googleapis.com/helloworld.HelloRequest", 
      PROTO_3, 
      null, 
      "helloworld.proto"
    ) {
      public override fun encodedSize(`value`: HelloRequest): Int {
        var size = value.unknownFields.size
        if (value.name != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.name)
        return size
      }

      public override fun encode(writer: ProtoWriter, `value`: HelloRequest): Unit {
        if (value.name != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.name)
        writer.writeBytes(value.unknownFields)
      }

      public override fun encode(writer: ReverseProtoWriter, `value`: HelloRequest): Unit {
        writer.writeBytes(value.unknownFields)
        if (value.name != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.name)
      }

      public override fun decode(reader: ProtoReader): HelloRequest {
        var name: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> name = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return HelloRequest(
          name = name,
          unknownFields = unknownFields
        )
      }

      public override fun redact(`value`: HelloRequest): HelloRequest = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
