// Code generated by Wire protocol buffer compiler, do not edit.
// Source: helloworld.HelloReply in helloworld.proto
package io.grpc.examples.helloworld

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Unit
import kotlin.jvm.JvmField
import okio.ByteString

/**
 * The response message containing the greetings.
 */
public class HelloReply(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
  )
  public val message: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<HelloReply, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  public override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is HelloReply) return false
    if (unknownFields != other.unknownFields) return false
    if (message != other.message) return false
    return true
  }

  public override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + message.hashCode()
      super.hashCode = result
    }
    return result
  }

  public override fun toString(): String {
    val result = mutableListOf<String>()
    result += """message=${sanitize(message)}"""
    return result.joinToString(prefix = "HelloReply{", separator = ", ", postfix = "}")
  }

  public fun copy(message: String = this.message, unknownFields: ByteString = this.unknownFields):
      HelloReply = HelloReply(message, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<HelloReply> = object : ProtoAdapter<HelloReply>(
      FieldEncoding.LENGTH_DELIMITED, 
      HelloReply::class, 
      "type.googleapis.com/helloworld.HelloReply", 
      PROTO_3, 
      null, 
      "helloworld.proto"
    ) {
      public override fun encodedSize(`value`: HelloReply): Int {
        var size = value.unknownFields.size
        if (value.message != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.message)
        return size
      }

      public override fun encode(writer: ProtoWriter, `value`: HelloReply): Unit {
        if (value.message != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.message)
        writer.writeBytes(value.unknownFields)
      }

      public override fun encode(writer: ReverseProtoWriter, `value`: HelloReply): Unit {
        writer.writeBytes(value.unknownFields)
        if (value.message != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.message)
      }

      public override fun decode(reader: ProtoReader): HelloReply {
        var message: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> message = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return HelloReply(
          message = message,
          unknownFields = unknownFields
        )
      }

      public override fun redact(`value`: HelloReply): HelloReply = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
